import { useEffect, useMemo, useState } from 'react'
import { Area, AreaChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Activity, ArrowUpRight, BatteryCharging, Car, CircleHelp, Gauge, Grid2X2, Layers3, Map, Menu, Pause, Play, RotateCcw, Settings2, TimerReset, Trophy, X } from 'lucide-react'
import { buildLap, drivers, formatLapTime, getSectorRange, getTireState, laps, sectors, sectorTime, type DriverId, type Lap, type SectorId, type TireState } from './data'
import './App.css'

function App() {
  const [driverId, setDriverId] = useState<DriverId>('ax01')
  const [lapNumber, setLapNumber] = useState(18)
  const [sector, setSector] = useState<SectorId>('all')
  const [activePage, setActivePage] = useState('Overview')
  const [isReplay, setIsReplay] = useState(false)
  const [isPlaying, setIsPlaying] = useState(false)
  const [sampleIndex, setSampleIndex] = useState(62)
  const [sidebarOpen, setSidebarOpen] = useState(false)
  const driver = drivers.find((item) => item.id === driverId) ?? drivers[0]
  const lap = useMemo(() => buildLap(driver, lapNumber), [driver, lapNumber])
  const point = lap.telemetry[sampleIndex] ?? lap.telemetry[0]
  const tireState = getTireState(driver, lap)
  const sectorRange = getSectorRange(sector)
  const chartData = lap.telemetry.map((item) => ({ ...item, selected: item.distance >= sectorRange[0] && item.distance <= sectorRange[1] ? item.speed : undefined }))

  useEffect(() => {
    if (!isPlaying) return undefined
    const timer = window.setInterval(() => setSampleIndex((current) => (current + 1) % lap.telemetry.length), 180)
    return () => window.clearInterval(timer)
  }, [isPlaying, lap.telemetry.length])

  const navItems = [
    { label: 'Overview', icon: Grid2X2 }, { label: 'Telemetry', icon: Activity }, { label: 'Lap Analysis', icon: TimerReset },
    { label: 'Drivers', icon: Trophy }, { label: 'Strategy', icon: Layers3 }, { label: 'Tires', icon: CircleHelp }, { label: 'Track', icon: Map },
  ]
  const metrics = [
    { label: 'Speed', value: point.speed, unit: 'KM/H', tone: 'red' }, { label: 'RPM', value: point.rpm.toLocaleString(), unit: 'REV/MIN' },
    { label: 'Throttle', value: `${point.throttle}%`, unit: 'INPUT' }, { label: 'Brake', value: `${point.brake}%`, unit: 'INPUT' },
    { label: 'Gear', value: point.gear, unit: 'SELECTED' }, { label: 'G-force', value: `${Math.abs(point.lateralG).toFixed(2)}`, unit: 'LATERAL G' },
  ]

  return (
    <div className="app-shell">
      <aside className={`sidebar ${sidebarOpen ? 'open' : ''}`}>
        <div className="brand"><span className="brand-mark">A</span><div><strong>APEX</strong><small>RACING INTELLIGENCE</small></div><button className="icon-button mobile-close" onClick={() => setSidebarOpen(false)} aria-label="Close navigation"><X size={16} /></button></div>
        <div className="session-badge"><span className="status-dot" /> SIMULATION ACTIVE <span className="session-code">04 / 018</span></div>
        <nav aria-label="Primary navigation">{navItems.map(({ label, icon: Icon }) => <button key={label} className={activePage === label ? 'nav-item active' : 'nav-item'} onClick={() => { setActivePage(label); setSidebarOpen(false) }}><Icon size={16} /><span>{label}</span>{activePage === label && <ArrowUpRight size={13} />}</button>)}</nav>
        <div className="sidebar-bottom"><button className="nav-item"><Settings2 size={16} /><span>Settings</span></button><div className="data-status"><div><span className="status-dot" /> DATA STREAM</div><strong>CONNECTED</strong><small>12,481 samples / SIM-042</small></div><small className="version">APEX OS v1.0 · FICTIONAL DATA ENVIRONMENT</small></div>
      </aside>
      <main className="main-canvas">
        <header className="topbar"><button className="icon-button menu-button" onClick={() => setSidebarOpen(true)} aria-label="Open navigation"><Menu size={19} /></button><div className="crumb"><span>SESSION / 04</span><strong>MONARCH GP CIRCUIT</strong></div><div className="selectors"><label>DRIVER<select value={driverId} onChange={(event) => { setDriverId(event.target.value as DriverId); setSampleIndex(0); setIsPlaying(false) }}>{drivers.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label><label>LAP<select value={lapNumber} onChange={(event) => { setLapNumber(Number(event.target.value)); setSampleIndex(0); setIsPlaying(false) }}>{laps.map((number) => <option key={number} value={number}>LAP {number}</option>)}</select></label><label>SECTOR<select value={sector} onChange={(event) => setSector(event.target.value as SectorId)}>{sectors.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label></div><div className="mode-toggle"><button className={!isReplay ? 'selected' : ''} onClick={() => { setIsReplay(false); setIsPlaying(false) }}>LIVE</button><button className={isReplay ? 'selected' : ''} onClick={() => setIsReplay(true)}>REPLAY</button></div><div className="updated"><span className="status-dot" /> LIVE<br /><small>UPDATED 14:32:08</small></div></header>
        <section className="content" data-page={activePage}>
          <div className="page-intro"><div><p className="eyebrow">{activePage.toUpperCase()} / TELEMETRY ENVIRONMENT</p><h1>Every lap<br /><em>tells a story.</em></h1><p className="intro-copy">Read the race beyond the stopwatch. Explore simulated telemetry across speed, precision, tire behavior, and the decisions that shape a lap.</p></div><div className="hero-car"><div className="track-line" /><div className="car-silhouette"><Car size={104} strokeWidth={1} /></div><span className="hero-coordinate">MONARCH GP / 5.842 KM / 18 CORNERS</span></div></div>
          {activePage !== 'Overview' && activePage !== 'Telemetry' && <AuxiliaryView page={activePage} driver={driver} lap={lap} tireState={tireState} />}
          <div className="telemetry-strip">{metrics.map((metric) => <div className={`strip-metric ${metric.tone ?? ''}`} key={metric.label}><span>{metric.label}</span><strong>{metric.value}</strong><small>{metric.unit}</small></div>)}</div>
          <div className="section-heading"><div><p className="eyebrow">01 / LIVE TELEMETRY</p><h2>Performance trace <span>/{driver.code} · LAP {lapNumber}</span></h2></div><div className="replay-controls">{isReplay && <><button className="icon-button" onClick={() => setSampleIndex(0)} aria-label="Restart replay"><RotateCcw size={15} /></button><button className="icon-button play" onClick={() => setIsPlaying((value) => !value)} aria-label={isPlaying ? 'Pause replay' : 'Play replay'}>{isPlaying ? <Pause size={15} /> : <Play size={15} />}</button><input aria-label="Replay position" type="range" min="0" max={lap.telemetry.length - 1} value={sampleIndex} onChange={(event) => setSampleIndex(Number(event.target.value))} /></>}</div></div>
          <div className="dashboard-grid"><section className="panel telemetry-panel"><div className="panel-header"><span>VELOCITY / RPM / INPUTS</span><small>DISTANCE {point.distance.toFixed(2)} KM</small></div><div className="chart-wrap"><ResponsiveContainer width="100%" height={245}><AreaChart data={chartData} onMouseMove={(event) => { if (typeof event.activeTooltipIndex === 'number') setSampleIndex(event.activeTooltipIndex) }}><defs><linearGradient id="speedFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#d75c52" stopOpacity={0.32} /><stop offset="100%" stopColor="#d75c52" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="#2a2d31" vertical={false} /><XAxis dataKey="distance" tick={{ fill: '#697078', fontSize: 10 }} tickLine={false} axisLine={false} /><YAxis domain={[80, 340]} tick={{ fill: '#697078', fontSize: 10 }} tickLine={false} axisLine={false} width={28} /><Tooltip content={<TelemetryTooltip />} /><Area type="monotone" dataKey="speed" stroke="#d75c52" fill="url(#speedFill)" strokeWidth={2} dot={false} activeDot={{ r: 4, fill: '#f6f4ef', stroke: '#d75c52' }} /><Line type="monotone" dataKey="selected" stroke="#f0c39b" strokeWidth={3} dot={false} connectNulls /></AreaChart></ResponsiveContainer></div><div className="chart-legend"><span><i className="legend-red" /> SPEED</span><span><i className="legend-gold" /> SELECTED SECTOR</span><span>KM / DISTANCE</span></div></section><TrackMap position={point.distance / 5.842} sector={sector} /><section className="panel mini-chart"><div className="panel-header"><span>ENGINE RESPONSE / RPM</span><Gauge size={15} /></div><ResponsiveContainer width="100%" height={115}><LineChart data={chartData}><CartesianGrid stroke="#292c30" vertical={false} /><XAxis dataKey="distance" hide /><YAxis domain={[4000, 11500]} hide /><Line dataKey="rpm" stroke="#82c6bf" strokeWidth={2} dot={false} /></LineChart></ResponsiveContainer><div className="mini-value"><strong>{point.rpm.toLocaleString()}</strong><span>REV/MIN</span></div></section><section className="panel mini-chart"><div className="panel-header"><span>G-FORCE VECTOR</span><Activity size={15} /></div><div className="g-force"><div className="g-crosshair" /><span className="g-marker" style={{ left: `${50 + point.lateralG * 24}%`, top: `${50 - point.longitudinalG * 24}%` }} /><strong>{Math.abs(point.lateralG).toFixed(2)} G</strong><small>LATERAL LOAD</small></div></section></div>
          <div className="lower-grid"><section className="panel sector-panel"><div className="panel-header"><span>SECTOR ANALYSIS</span><small>SIMULATED / OBJECTIVE</small></div><div className="sector-list">{(['s1', 's2', 's3'] as SectorId[]).map((item) => <button key={item} className={sector === item ? 'sector-row selected' : 'sector-row'} onClick={() => setSector(item)}><span>{item.toUpperCase()}</span><strong>{formatLapTime(sectorTime(lap, item)).slice(2)}</strong><small>{item === 's1' ? 'BRAKING / T1-T4' : item === 's2' ? 'HIGH SPEED / T5-T11' : 'TECHNICAL / T12-T18'}</small><b>{item === 's1' ? '+0.042' : item === 's2' ? '-0.118' : '+0.006'}</b></button>)}</div><div className="total-time"><span>LAP {lapNumber} / TOTAL</span><strong>{formatLapTime(lap.time)}</strong><small>BEST SESSION <b>1:28.431</b></small></div></section><section className="panel summary-panel"><div className="panel-header"><span>SESSION SUMMARY</span><span className="panel-live"><span className="status-dot" /> DATA VERIFIED</span></div><div className="summary-list"><SummaryItem icon={<TimerReset size={16} />} label="Best lap" value={formatLapTime(Math.min(lap.time, 88.431))} /><SummaryItem icon={<Gauge size={16} />} label="Top speed" value={`${lap.topSpeed} km/h`} /><SummaryItem icon={<BatteryCharging size={16} />} label="Fuel remaining" value={`${point.fuel.toFixed(1)} L`} /><SummaryItem icon={<Car size={16} />} label="Tire state" value={`${tireState.compound} / ${tireState.wear}% wear`} /></div><div className="driver-note"><span className="driver-avatar" style={{ background: driver.color }}>{driver.code.slice(0, 1)}</span><div><strong>{driver.name} · {driver.team}</strong><small>{driver.style} / consistency index {Math.round(driver.consistency * 100)}%</small></div></div></section></div>
          <footer><span>APEX / RACING TELEMETRY INTELLIGENCE SYSTEM</span><span>ALL DATA SIMULATED · DATASET / SIM-042</span><span>VERSION 1.0</span></footer>
        </section>
      </main>
    </div>
  )
}

function SummaryItem({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="summary-item"><span className="summary-icon">{icon}</span><div><small>{label}</small><strong>{value}</strong></div></div> }
function TelemetryTooltip({ active, payload, label }: { active?: boolean; payload?: Array<{ value: number; dataKey: string; payload?: Record<string, number> }>; label?: number }) { const point = payload?.[0]?.payload; if (!active || !point) return null; return <div className="tooltip"><small>{Number(label).toFixed(2)} KM / TRACE POSITION</small><strong>{point.speed} <i>KM/H</i></strong><div className="tooltip-grid"><span>RPM <b>{point.rpm.toLocaleString()}</b></span><span>THROTTLE <b>{point.throttle}%</b></span><span>BRAKE <b>{point.brake}%</b></span><span>GEAR <b>{point.gear}</b></span><span>G-FORCE <b>{Math.abs(point.lateralG).toFixed(2)} G</b></span></div></div> }
function TrackMap({ position, sector }: { position: number; sector: SectorId }) { return <section className="panel track-panel"><div className="panel-header"><span>LIVE TRACK / MONARCH GP</span><Map size={15} /></div><div className="track-canvas"><svg viewBox="0 0 560 250" role="img" aria-label="Stylized Monarch GP circuit map"><path className="track-shadow" d="M73 181 C34 144 55 66 126 56 C177 48 186 101 232 91 C284 79 273 34 350 35 C426 36 502 71 478 135 C461 180 407 180 376 153 C341 123 332 176 277 185 C213 195 159 198 73 181Z" /><path className="circuit" d="M73 181 C34 144 55 66 126 56 C177 48 186 101 232 91 C284 79 273 34 350 35 C426 36 502 71 478 135 C461 180 407 180 376 153 C341 123 332 176 277 185 C213 195 159 198 73 181Z" /><path className={sector === 's2' ? 'circuit selected-track' : 'racing-line'} d="M73 181 C34 144 55 66 126 56 C177 48 186 101 232 91 C284 79 273 34 350 35 C426 36 502 71 478 135 C461 180 407 180 376 153 C341 123 332 176 277 185 C213 195 159 198 73 181Z" /><circle className="car-marker" cx={73 + Math.sin(position * Math.PI * 2) * 180} cy={122 + Math.cos(position * Math.PI * 2) * 65} r="5" /></svg><div className="track-key"><span><i className="key-line" /> RACING LINE</span><span><i className="key-dot" /> CAR / {(position * 5.842).toFixed(2)} KM</span></div><div className="track-label s1">S1</div><div className="track-label s2">S2</div><div className="track-label s3">S3</div></div></section> }

function AuxiliaryView({ page, driver, lap, tireState }: { page: string; driver: typeof drivers[number]; lap: Lap; tireState: TireState }) {
  if (page === 'Lap Analysis') return <section className="analysis-view"><div className="analysis-heading"><div><p className="eyebrow">02 / LAP ANALYSIS</p><h2>Rhythm over a single number.</h2></div><span className="sim-tag">SIMULATED / LAP {lap.number}</span></div><div className="analysis-grid"><div className="analysis-stat"><small>LAP TIME</small><strong>{formatLapTime(lap.time)}</strong><span>-0.118 vs session reference</span></div><div className="analysis-stat"><small>AVERAGE SPEED</small><strong>{lap.averageSpeed} <i>KM/H</i></strong><span>Peak {lap.topSpeed} km/h</span></div><div className="analysis-stat"><small>COMPOUND</small><strong>{lap.compound}</strong><span>{tireState.wear}% wear at lap end</span></div></div><div className="lap-bars">{laps.map((number) => <button className={number === lap.number ? 'lap-bar active' : 'lap-bar'} key={number} aria-label={`Load lap ${number}`}><span style={{ height: `${42 + ((number * 17) % 46)}%` }} /><small>{number}</small></button>)}</div></section>
  if (page === 'Drivers') return <section className="analysis-view"><div className="analysis-heading"><div><p className="eyebrow">03 / DRIVER COMPARISON</p><h2>Different inputs. Same circuit.</h2></div><span className="sim-tag">OBJECTIVE TELEMETRY</span></div><div className="driver-compare">{drivers.map((item) => { const itemLap = buildLap(item, lap.number); return <article className={item.id === driver.id ? 'driver-compare-card current' : 'driver-compare-card'} key={item.id}><div className="driver-identity"><span className="driver-avatar" style={{ background: item.color }}>{item.code.slice(0, 1)}</span><div><strong>{item.name}</strong><small>{item.code} / {item.style}</small></div></div><dl><div><dt>BEST LAP</dt><dd>{formatLapTime(itemLap.time)}</dd></div><div><dt>TOP SPEED</dt><dd>{itemLap.topSpeed} <i>KM/H</i></dd></div><div><dt>CONSISTENCY</dt><dd>{Math.round(item.consistency * 100)}%</dd></div></dl></article> })}</div></section>
  if (page === 'Tires') return <section className="analysis-view"><div className="analysis-heading"><div><p className="eyebrow">04 / TIRE ANALYSIS</p><h2>Grip is a moving target.</h2></div><span className="sim-tag">{tireState.compound} / SIMULATED</span></div><div className="tire-grid">{['FL', 'FR', 'RL', 'RR'].map((wheel, index) => <div className="tire-cell" key={wheel}><div className="tire-label"><strong>{wheel}</strong><span>{tireState.temperature + index - 1}°C</span></div><div className="tire-meter"><span style={{ width: `${Math.min(92, tireState.wear + 38 + index * 4)}%` }} /></div><small>WEAR {Math.min(92, tireState.wear + index * 4)}% / DEG {tireState.degradation.toFixed(1)}%</small></div>)}</div></section>
  if (page === 'Strategy') return <section className="analysis-view"><div className="analysis-heading"><div><p className="eyebrow">05 / RACE STRATEGY</p><h2>Manage the window.</h2></div><span className="sim-tag">MONARCH GP / 52 LAPS</span></div><div className="strategy-timeline"><div className="strategy-stint active"><strong>STINT 01</strong><span>MEDIUM</span><small>LAP 01 — 17 / 17 LAPS</small></div><div className="pit-marker">PIT<br /><b>18</b></div><div className="strategy-stint"><strong>STINT 02</strong><span>HARD</span><small>LAP 18 — 39 / 22 LAPS</small></div><div className="pit-marker">PIT<br /><b>40</b></div><div className="strategy-stint"><strong>STINT 03</strong><span>MEDIUM</span><small>LAP 40 — 52 / 13 LAPS</small></div></div></section>
  return <section className="analysis-view track-detail"><div className="analysis-heading"><div><p className="eyebrow">06 / TRACK INTELLIGENCE</p><h2>Monarch GP, sector by sector.</h2></div><span className="sim-tag">5.842 KM / 18 CORNERS</span></div><div className="track-facts"><span><strong>01:28.431</strong><small>SESSION BEST</small></span><span><strong>318 <i>KM/H</i></strong><small>TOP SPEED</small></span><span><strong>18</strong><small>CORNERS</small></span><span><strong>3</strong><small>SECTORS</small></span></div></section>
}

export default App
